const API_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1ZDI0NjRjMWRhZWU5MGViMDg1YjMzYWI1MmNmOGM2MSIsIm5iZiI6MTc4NTA4NTYyOS4yNzAwMDAyLCJzdWIiOiI2YTY2M2ViZDI1ZTU4NWQxMjZiZDk0MjgiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.4ab1FI96JkD-ZNYl4FVBDDWcVYi7AXvABAdcohNESsU";
const BASE_URL = "https://api.themoviedb.org/3";

const IMAGE_URL = "https://image.tmdb.org/t/p/w500";